name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.7'
          - '3.8'
          - '3.9'
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Install rusty_results
        run: pip install -e .
      - name: Run tests with pytest
        run: pytest
      - name: Run mypy on result.py
        run: mypy rusty_results/prelude.py
      - name: Build coverage file
      run: |
        pytest --cache-clear --cov=app ./rusty_results > pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2