name: Publish docs
on:
  push:
    branches:
      - main


# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: Install pdoc
      run: pip install pdoc3

    # Build the book
    - name: Build docs
      run: pdoc --html --output-dir docs rusty_results

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/rusty_results